-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at httpsredmine.postgresql.orgprojectspgadmin4issuesnew if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.Orders
(
    id integer NOT NULL,
    product_id integer NOT NULL,
    adres_id integer NOT NULL,
    user_phone_number character varying(20) NOT NULL,
    delivery_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.Products
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description text NOT NULL,
    stock_code character varying(13) NOT NULL,
    category_id integer NOT NULL,
    inventory_id integer NOT NULL,
    price double precision NOT NULL,
    discount_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.Users
(
    id integer NOT NULL,
    user_name character varying(15) NOT NULL,
    password character varying(25) NOT NULL,
    first_name character varying(15) NOT NULL,
    last_name character varying(15) NOT NULL,
    phone_number character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.discount
(
    id integer NOT NULL,
    product_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.inventory
(
    id integer NOT NULL,
    quantity character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.order_destails
(
    id integer NOT NULL,
    product_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.product_category
(
    id integer NOT NULL,
    name character varying(23),
    description character varying(250),
    PRIMARY KEY (id)
);

CREATE TABLE public.user_address
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    adres_line1 character varying(120) NOT NULL,
    adres_line2 character varying(50) NOT NULL,
    zipcode char NOT NULL,
    country name NOT NULL,
    phone integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.user_payment
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    payment_type character varying(50) NOT NULL,
    provider character varying(25) NOT NULL,
    account_no character varying(25) NOT NULL,
    vade date NOT NULL,
    payment_detail character varying(240) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.Orders
    ADD FOREIGN KEY (adres_id)
    REFERENCES public.user_address (id)
    NOT VALID;


ALTER TABLE public.Orders
    ADD FOREIGN KEY (product_id)
    REFERENCES public.Products (id)
    NOT VALID;


ALTER TABLE public.Products
    ADD FOREIGN KEY (category_id)
    REFERENCES public.product_category (id)
    NOT VALID;


ALTER TABLE public.Products
    ADD FOREIGN KEY (category_id)
    REFERENCES public.product_category (id)
    NOT VALID;


ALTER TABLE public.Products
    ADD FOREIGN KEY (discount_id)
    REFERENCES public.discount (id)
    NOT VALID;


ALTER TABLE public.Products
    ADD FOREIGN KEY (inventory_id)
    REFERENCES public.inventory (id)
    NOT VALID;


ALTER TABLE public.order_destails
    ADD FOREIGN KEY (product_id)
    REFERENCES public.Products (id)
    NOT VALID;


ALTER TABLE public.user_address
    ADD FOREIGN KEY (user_id)
    REFERENCES public.Users (id)
    NOT VALID;


ALTER TABLE public.user_payment
    ADD FOREIGN KEY (user_id)
    REFERENCES public.Users (id)
    NOT VALID;


ALTER TABLE public.user_payment
    ADD FOREIGN KEY (user_id)
    REFERENCES public.Users (id)
    NOT VALID;

END;